# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6d10bcbf-fda3-4f5e-aaf4-e2590681216c'
  imageRepository: 'dsmsprojectdotnetaks'
  containerRegistry: 'desattiracr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '2900'
  imagePullSecret: 'desattiracr12104330-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  k8sNamespaceForPR: '$(system.pullRequest.sourceBranch)'

stages:

- stage: Deploy
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'dsmsprojectdotnetaks.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          
          - script: |
              cd $(Agent.TempDirectory)
              helm create app-deploy-chart
          
          - task: AzureCLI@1
            displayName: get host suffix
            inputs:
              azureSubscription: RMDev
              inlineScript: |
                 $out=$(az aks list --query "[?name == 'desattir'][addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName]" | ConvertFrom-Json)
                 if ($out.Length -eq 0) { 
                    Write-Host "Ensure your AKS cluster still exists";
                    exit 1;
                 }
                 if ($out.Length -ge 1) { 
                    Write-Host "There's a conflict, add --resource-group flag to the list command";
                    exit 1
                 }
                 if ($out[0][0]) {
                    $hostSuffix=$out[0][0]
                    Write-Host "##vso[task.setvariable variable=HostSuffix]${hostSuffix}"
                 }
                 else {
                    Write-Host "Enable addon http routing"
                    exit 1;
                 }
            

          - task: KubernetesManifest@0
            displayName: Bake manifests
            name: bake
            inputs:
              helmChart: $(Agent.TempDirectory)/app-deploy-chart
              overrideFiles: $(Agent.TempDirectory)/app-deploy-chart/values.yaml
              overrides: |
                image.repository:$(containerRegistry)/$(imageRepository)
                service.port:80
                ingress.enabled:true
                ingress.annotations.kuberentes.io/ingress.class:addon-http-application-routing
                ingress.path:/
                ingress.hostname:app-deploy.$(HostSuffix)

          - script: cat $(bake.manifestsBundle)
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(bake.manifestsBundle)
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

  - deployment: DeployPR
    displayName: Deploy PR
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: $(vmImageName)
      
    environment: 'dsmsprojectdotnetaks.$(k8sNamespaceForPR)'
    strategy:
      runOnce:
        deploy:
          steps:
          - reviewApp: default

          - task: Kubernetes@1
            displayName: 'kubectl create namespace'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(k8sNamespaceForPR)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespaceForPR)
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
          
          - task: Kubernetes@1
            name: get
            displayName: 'kubectl get services'
            inputs:
              command: get
              namespace: $(k8sNamespaceForPR)
              arguments: svc
          
          - powershell: |
              $service=$(echo '$(get.KubectlOutput)' |  Out-String | ConvertFrom-Json).items[0]
              $ip=$service.status.loadBalancer.ingress.ip
              $port=$service.spec.ports.port
              $message="Deployment to your review-app succeeded."
              if($ip) {$message="${message}<br><br>You can navigate to http://${ip}:${port} to test your changes"}
              echo "##vso[task.setvariable variable=GITHUB_COMMENT]${message}"

