apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dsmsprojectdotnetaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dsmsprojectdotnetaks 
    spec:
      containers:
        - name: dsmsprojectdotnetaks 
          image: desattiracr.azurecr.io/dsmsprojectdotnetaks
          ports:
          - containerPort: 80